# Generated by Django 5.0.3 on 2024-03-31 10:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_category_options_order_is_sale_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 3, 31, 10, 30, 5, 90320, tzinfo=datetime.timezone.utc)),
        ),
    ]
