# Generated by Django 5.0.3 on 2024-03-31 10:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_order_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='is_sale',
        ),
        migrations.RemoveField(
            model_name='order',
            name='sale_price',
        ),
        migrations.AddField(
            model_name='product',
            name='is_sale',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='sale_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 3, 31, 10, 34, 2, 478160, tzinfo=datetime.timezone.utc)),
        ),
    ]
